#! /bin/sh
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Tomcat
# Description: This file starts and stops Tomcat server
# 
### END INIT INFO

TOMCAT_DIR=/home/joe/programs/apache-tomcat-8.0.5/
export JAVA_HOME=/home/joe/programs/jdk1.8.0_05

case "$1" in
 start)
   (cd $HOME/FaceDetectionApp/; sudo docker-compose up --build)
   ;;
 stop)
   (cd $HOME/FaceDetectionApp/; sudo docker-compose stop)
   sleep 10
   ;;
 restart)
   (cd $HOME/FaceDetectionApp/; sudo docker-compose stop)
   sleep 20
   (cd $HOME/FaceDetectionApp/; sudo docker-compose up --build)
   ;;
 *)
   echo "Usage: tomcat {start|stop|restart}" >&2
   exit 3
   ;;
esac
